# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Laneast dog walking and pet sitting services
email: hello@laneastdogwalkingservices.co.uk
description: >- # this means to ignore newlines until "baseurl:"
  Professional dog walking and pet sitting in the PL15 postal area and beyond
  <!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-G00ECP5TDX"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-G00ECP5TDX');
</script>
  
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "https://www.laneastdogwalkingservices.co.uk/"
# Build settings
copyright: Copyright Laneast dog walking and pet sitting <script src="/assets/js/forcenavopen.js"/>
logo: "/assets/images/logo.png"
#theme: jekyll-theme-so-simple
remote_theme: "mmistakes/so-simple-theme@3.2.0"
plugins:
  - jekyll-feed
  - jekyll-remote-theme
exclude:
 - jekyllserve.cmd


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
